version: '3.3'
volumes:
  postgres-data:
services:
  postgres:
    image: cr.yandex/crpm1djccivqbcnoahla/postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: popolodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./packages/db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - 5432:5432
  server:
    image: cr.yandex/crpm1djccivqbcnoahla/popolo-grasso_server
    restart: always
    ports:
      - 443:443
    depends_on: 
     - postgres
