version: '3.3'
volumes:
  postgres-data:
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: popolodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./packages/db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - 5432:5432
  # server:
  #   restart: always
  #   ports:
  #     - 3009:3008
  #   build:
  #     context: ./
  #   depends_on: 
  #    - postgres
