version: '3.3'
volumes:
  postgres-data:
services:
  popolo-db:
    container_name: popolo-db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: popolodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./packages/db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - 5432:5432

  popolo-app:
    container_name: popolo-app
    build:
      context: ./
    restart: always
    ports:
      - 3008:3008
    depends_on: 
     - popolo-db

  popolo-proxy:
    build:
      context: ./packages/nginx
    container_name: popolo-proxy
    restart: always
    ports:
      - 80:80
      # - 443:443
networks:
  default:
    driver: bridge