name: CI-CD-to-Yandex-cloud
env:
  REGISTRY_ID: "crpm1djccivqbcnoahla"
  APP_IMAGE_TAG: "popolo-grasso_server"
  POSTGRESS_IMAGE_TAG: "postgres:12"

on:
  push:
    branches: ["master"]

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v1

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.SA_TOKEN }}

      - name: Build with docker-compose
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Tag and pull to registry
        run: |
          docker tag ${{ env.APP_IMAGE_TAG }}       cr.yandex/${{ env.REGISTRY_ID }}/${{ env.APP_IMAGE_TAG }}
          docker tag ${{ env.POSTGRESS_IMAGE_TAG }} cr.yandex/${{ env.REGISTRY_ID }}/${{ env.POSTGRESS_IMAGE_TAG }}

          docker push cr.yandex/${{ env.REGISTRY_ID }}/${{ env.APP_IMAGE_TAG }}
          docker push cr.yandex/${{ env.REGISTRY_ID }}/${{ env.POSTGRESS_IMAGE_TAG }}

      - name: Connect to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # на VPS лежит собственный compose. Он идентичен текущему,
          # но берет image's из yc-registry
          script: docker-compose -f docker-compose.yml up --build -d
