name: CI-CD-to-Yandex-cloud
env: 
  REGISTRY_ID: "crpm1djccivqbcnoahla"
  APP_IMAGE_TAG: "cr.yandex/${{ env.REGISTRY_ID }}/popolo-grasso_server:latest"
  POSTGRESS_IMAGE_TAG: "cr.yandex/${{ env.REGISTRY_ID }}/postgres:12"
  
on:
  push:
    branches: [ "#90/ci" ]

jobs:
  ci_pipeline: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.SA_TOKEN }}

      - name: Git clone repo
        uses: actions/checkout@v1
        
      - name: Build with docker-compose  
        run: docker-compose -f docker-compose.yml up --build -d
        
      - name: Tag and pull to registry
        run: |
          docker tag popolo-grasso_server ${{ APP_IMAGE_TAG }}
          docker tag postgres:12 ${{ POSTGRESS_IMAGE_TAG }}
          docker push ${{ APP_IMAGE_TAG }}
          docker push ${{ POSTGRESS_IMAGE_TAG }}
 
